### ISSUE TITLE
Currently cant migrate.

### ISSUE THREAD

**Issue by h14turkiye** [JustSxm/SpotifyMigrator#9]
```$ sudo dotnet SpotifyMigrator.Server.dll
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[62]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/h14turkiye/Downloads/spotifymigator
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 304 - text/html 80.1350ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.webassembly.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - - - 304 - text/javascript 15.8524ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/blazor.boot.json.br'. Physical path: '/home/h14turkiye/Downloads/spotifymigator/wwwroot/_framework/blazor.boot.json.br'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - - - 200 3905 application/json 12.9978ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/appsettings.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /appsettings.json was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/appsettings.json - - - 304 - application/json 0.3286ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/dotnet.7.0.4.3fbokqc6ot.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - - - 304 - text/javascript 0.4625ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/api/Spotify?code=AQAD5__01qgA6EqSF1qm9ho-fJWjGO5UOPGqurOCBCbzE3EKURvRBTHjFAYB1-p5r6wCRk6B-PC0FA6htvDGxCfykJ2fFkhzU--kYEjSfNFWyFaLQPnQqDXvz--dlzIEqbbu2uZ06Of5gpgwnre92pgpcwrG9tyG3pESBbnLz5n9gg371DvA2IaEtqiL7qPRblS-9hwpbXRIIbOYcNgX-40o5DRsNISLPkO94xWAll1X9gRuNZGVk2rkycSUw9V8YsfeB-QspZp3HE8ure9TUbQqdtUx8GIol4rHXXJc1pZ7T_1nRNVwDJfW93MtDmgKcpKN348lPamRtnEmu_eAsU9GVhy1CIVyzgNCZGEOR63lKPKlJjkFJrEljwwxABgoqPy6eQ - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "GetAuthentificationResponse", controller = "Spotify"}. Executing controller action with signature System.Threading.Tasks.Task GetAuthentificationResponse(System.String) on controller SpotifyMigrator.Server.Controllers.SpotifyController (SpotifyMigrator.Server).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server) in 862.9029ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/api/Spotify?code=AQAD5__01qgA6EqSF1qm9ho-fJWjGO5UOPGqurOCBCbzE3EKURvRBTHjFAYB1-p5r6wCRk6B-PC0FA6htvDGxCfykJ2fFkhzU--kYEjSfNFWyFaLQPnQqDXvz--dlzIEqbbu2uZ06Of5gpgwnre92pgpcwrG9tyG3pESBbnLz5n9gg371DvA2IaEtqiL7qPRblS-9hwpbXRIIbOYcNgX-40o5DRsNISLPkO94xWAll1X9gRuNZGVk2rkycSUw9V8YsfeB-QspZp3HE8ure9TUbQqdtUx8GIol4rHXXJc1pZ7T_1nRNVwDJfW93MtDmgKcpKN348lPamRtnEmu_eAsU9GVhy1CIVyzgNCZGEOR63lKPKlJjkFJrEljwwxABgoqPy6eQ - - - 302 0 - 901.5501ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/home - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/index.html'. Physical path: '/home/h14turkiye/Downloads/spotifymigator/wwwroot/index.html'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/home - - - 200 - text/html 21.2181ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.webassembly.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - - - 304 - text/javascript 0.4469ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.boot.json.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - - - 304 - application/json 0.3948ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/appsettings.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /appsettings.json was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/appsettings.json - - - 304 - application/json 0.2852ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/dotnet.7.0.4.3fbokqc6ot.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - - - 304 - text/javascript 0.3857ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/api/Spotify?code=AQCUyEgnHj6ATJ5NKGynhwXxTkfz30f_3lfmx_O3yY9yFg13TRSVkJ3Xxwq8SGHrB4xV_DAIuw_Tdo3HfkqNGRbpLi0bYDxdSuutS2EvXPTkCcRqMWqyOy8YXj71w-IWEciZFOqhBE8bFpU5_F4Trvo1SH1JAI1UD1KlG-S03KN5OYtVMxX2WjpHXy12FS2Qviu-YeQrSc-14HIBxOol5PrnFf6-DWG1YcOc8bHeLO2_O8ivOxPMpIEOAvCnlR0aLF6zIzrlZRvV_QDTLLIQAWiWXA4nMuUJDnze3OeA7fH8Y7RVOhepQGY2jOWHHede-7oP_UvkkSR3cKOLF0A5Ygt650vziLEy-YaJ_9yYD5cE1BHVlJUSNU6jnVWZK_Y6dZZBLQ - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "GetAuthentificationResponse", controller = "Spotify"}. Executing controller action with signature System.Threading.Tasks.Task GetAuthentificationResponse(System.String) on controller SpotifyMigrator.Server.Controllers.SpotifyController (SpotifyMigrator.Server).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server) in 426.7287ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.GetAuthentificationResponse (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/api/Spotify?code=AQCUyEgnHj6ATJ5NKGynhwXxTkfz30f_3lfmx_O3yY9yFg13TRSVkJ3Xxwq8SGHrB4xV_DAIuw_Tdo3HfkqNGRbpLi0bYDxdSuutS2EvXPTkCcRqMWqyOy8YXj71w-IWEciZFOqhBE8bFpU5_F4Trvo1SH1JAI1UD1KlG-S03KN5OYtVMxX2WjpHXy12FS2Qviu-YeQrSc-14HIBxOol5PrnFf6-DWG1YcOc8bHeLO2_O8ivOxPMpIEOAvCnlR0aLF6zIzrlZRvV_QDTLLIQAWiWXA4nMuUJDnze3OeA7fH8Y7RVOhepQGY2jOWHHede-7oP_UvkkSR3cKOLF0A5Ygt650vziLEy-YaJ_9yYD5cE1BHVlJUSNU6jnVWZK_Y6dZZBLQ - - - 302 0 - 427.6792ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/homemigrate - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/index.html'. Physical path: '/home/h14turkiye/Downloads/spotifymigator/wwwroot/index.html'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/homemigrate - - - 200 - text/html 6.9180ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/blazor.webassembly.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.webassembly.js - - - 304 - text/javascript 0.3948ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/_framework/blazor.boot.json.br'. Physical path: '/home/h14turkiye/Downloads/spotifymigator/wwwroot/_framework/blazor.boot.json.br'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/blazor.boot.json - - - 200 3905 application/json 4.0042ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/appsettings.json - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /appsettings.json was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/appsettings.json - - - 304 - application/json 0.3848ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - -
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /_framework/dotnet.7.0.4.3fbokqc6ot.js.br was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/_framework/dotnet.7.0.4.3fbokqc6ot.js - - - 304 - text/javascript 0.3544ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5000/hub/negotiate?negotiateVersion=1 - 0
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/hub/negotiate'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/hub/negotiate'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5000/hub/negotiate?negotiateVersion=1 - 0 - 200 - application/json 7.1273ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/hub?id=TC-aP0Ejnlwabo-mpKOe8g - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/hub'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5000/api/Spotify/MigrateAccount application/json;+charset=utf-8 37
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.MigrateAccount (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "MigrateAccount", controller = "Spotify"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] MigrateAccount(SpotifyMigrator.Shared.MigrateStartDTO) on controller SpotifyMigrator.Server.Controllers.SpotifyController (SpotifyMigrator.Server).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing StatusCodeResult, setting HTTP status code 200
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action SpotifyMigrator.Server.Controllers.SpotifyController.MigrateAccount (SpotifyMigrator.Server) in 53.5087ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'SpotifyMigrator.Server.Controllers.SpotifyController.MigrateAccount (SpotifyMigrator.Server)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5000/api/Spotify/MigrateAccount application/json;+charset=utf-8 37 - 200 0 - 60.9946ms
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SpotifyMigrator.Server.SignalRWorker.Migrate() in C:\Users\ShushImSam\Desktop\Folders\Projects\SpotifyMigrator\SpotifyMigrator\Server\SignalRWorker.cs:line 85
         at SpotifyMigrator.Server.SignalRWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\ShushImSam\Desktop\Folders\Projects\SpotifyMigrator\SpotifyMigrator\Server\SignalRWorker.cs:line 31
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SpotifyMigrator.Server.SignalRWorker.Migrate() in C:\Users\ShushImSam\Desktop\Folders\Projects\SpotifyMigrator\SpotifyMigrator\Server\SignalRWorker.cs:line 85
         at SpotifyMigrator.Server.SignalRWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\ShushImSam\Desktop\Folders\Projects\SpotifyMigrator\SpotifyMigrator\Server\SignalRWorker.cs:line 31
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/hub'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/hub?id=TC-aP0Ejnlwabo-mpKOe8g - - - 101 - - 12456.9265ms
```

I think this happens when there is 100+ songs in a single playlist.

**Comment by JustSxm** [comment]
I have 2000+ songs in my liked songs and I never had a problem. 

What exactly are you doing when this error occurs?

**Comment by h14turkiye** [comment]
I'm copying my playlists to my new account, It crashes at 10/22, 100 songs into the playlist.

**Comment by JustSxm** [comment]
Thought it would be.

Try adding

`"Urls": "http://localhost:5009"`

To the Client/wwwroot/appsettings.json

If it doesn't work, remove what you've just added and try it with Server/appsettings.json instead.

I havent maintained this project in a while, but it should still work
